secure_password/config/routes.rb
SecurePassword::Application.routes.draw do
  resource :sessions
  resources :users

end

secure_password/app/models/session.rb
class Session 
	include ActiveModel::Validations
	include ActiveModel::Conversion
	extend ActiveModel::Naming

	attr_accessor :name, :password

	validates :name, :password, presence: true

	def initialize(attributes = {})
		attributes.each do |name, value|
			send("#{name}=".to_sym, value)
		end		
	end
	def persisted?
		false
	end
end

secure_password/app/models/user.rb
class User < ActiveRecord::Base
	has_secure_password
	def self.login(user_name, password)
		find_by_name(user_name).try(:authenticate,password)
	end
end

secure_password/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery #with: :exception
  before_filter :need_login, unless: -> {
  	controller_name == 'sessions'
  }
  protected
  def need_login
  	unless already_logged_in?
  		session[:requested_url] = request.url
  		redirect_to new_sessions_path 
  end
end  
  	def already_logged_in?
  		!session[:user_id].nil?  			
  		end	
  	end

secure_password/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def new
		@session = Session.new
	end

	def create
		@session = Session.new(params[:session])
		#@session = Session.new(params.require(:session).permit(:name, :password))
		if @session.valid?
			@user = User.login(@session.name, @session.password)
			if @user
				session[:user_id] = @user.id
				session[:user_name] = @user.name
				session[:user_display] = @user.display_name
				redirect_to session[:requested_url] || root_path
			else
				redirect_to new_sessions_path, :notice => "Falha no Login"
			end
		else
			render :new
		end
	end

	def destroy
		session[:user_id] = nil
		session[:user_name] = nil
		session[:user_display] = nil	
		redirect_to new_sessions_path		
end
end

secure_password/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :display_name, :password_digest)
    end
end

secure_password/app/helpers/application_helper.rb
module ApplicationHelper
end

secure_password/app/helpers/sessions_helper.rb
module SessionsHelper
end

secure_password/app/helpers/users_helper.rb
module UsersHelper
end

secure_password/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MyFirstApplication</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<header>
		<h1> Acesso ao Sistema </h1>
		<% if session[:user_id] %>
		<%= link_to "Logout", sessions_path, method: :delete %> Seja Bem-Vindo Usuário: <%= session[:user_display] %>
		<% else %>
		<%= link_to "Login", new_sessions_path %>
		<% end %>
	</header>
	<session id="main">
	<% if flash[:notice] %>
	<div class="notice"><%= flash[:notice] %></div>
	<% end %>
	<%= yield %>
</session>
</body>
</html>

secure_password/app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :Nome %><br>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :Nome_do_Usuário %><br>
    <%= f.text_field :display_name %>
  </div>

  <div class="field">
    <%= f.label :Senha %><br>
    <%= f.password_field :password %>
  </div>

  <div class="field">
    <%= f.label :Confirmação_da_Senha %><br>
    <%= f.password_field :password_confirmation %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>

  <% end %>

secure_password/app/views/users/edit.html.erb
<h1>Editar Usuário</h1>

<%= render 'form' %>

<%= link_to 'Mostar', @user %> |
<%= link_to 'Voltar', users_path %>

secure_password/app/views/users/index.html.erb
<h1>Lista de Usuários</h1>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th>Nome do Usuário</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.display_name %></td>
        
        <td><%= link_to 'Exibir', user %></td>
        <td><%= link_to 'Editar', edit_user_path(user) %></td>
        <td><%= link_to 'Excluir', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Novo Usuário', new_user_path %>

secure_password/app/views/users/new.html.erb
<h1>Novo Usuário</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

secure_password/app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Nome do Usuário:</strong>
  <%= @user.display_name %>
</p>

<%= link_to 'Editar', edit_user_path(@user) %> |
<%= link_to 'Voltar', users_path %>